apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: SERVICE_NAME
  labels:
    managed-by: ctr-prediction-deployment
    deployment-date: DEPLOYMENT_DATE
spec:
  template:
    metadata:
      labels:
        managed-by: ctr-prediction-deployment
        deployment-date: DEPLOYMENT_DATE
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: IMAGE_URL
        resources:
          limits:
            cpu: CPU_LIMIT
            memory: MEMORY_LIMIT
        env:
        - name: ENV_VAR_NAME
          value: ENV_VAR_VALUE

